services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mycalendar:latest
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks: [web]

  caddy:
    image: caddy:2
    restart: unless-stopped
    depends_on: [app]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks: [web]

  duckdns:
    image: ghcr.io/linuxserver/duckdns
    restart: unless-stopped
    env_file: .env       # ⬅️ we'll create this next
    environment:
      - SUBDOMAINS=${DUCKDNS_SUBDOMAINS}
      - TOKEN=${DUCKDNS_TOKEN}
      - TZ=${TZ}
    networks: [web]

networks:
  web:

volumes:
  caddy_data:
  caddy_config:
